services:
  - type: web
    name: cloudreve
    env: docker
    repo: https://github.com/Sakura1943/cloudreve-render.git
    region: oregon
    plan: free
    healthCheckPath: /
    envVars:
    - key: DB_PORT
      # value:
      sync: false
    - key: DB_TYPE
      # value:
      sync: false
    - key: DB_USER
      # value:
      sync: false
    - key: DB_PASSWORD
      # value:
      sync: false
    - key: DB_NAME
      # value:
      sync: false
    - key: DB_HOST
      # value:
      sync: false
    - key: DB_TABLEPREFIX
      # value:
      sync: false
